#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Warcaby.Resource", IsApplication=true)]

namespace Warcaby
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int biale = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int czarne = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int czarne_biale = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int czarne_biale_dama = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int czarne_biale_dama_zazn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int czarne_biale_zazn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int czarne_czarne = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int czarne_czarne_dama = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int czarne_czarne_dama_zazn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int czarne_czarne_zazn = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050038
			public const int field_00 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int field_01 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int field_02 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int field_03 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int field_04 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int field_05 = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int field_06 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int field_07 = 2131034175;
			
			// aapt resource value: 0x7f050030
			public const int field_10 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int field_11 = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int field_12 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int field_13 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int field_14 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int field_15 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int field_16 = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int field_17 = 2131034167;
			
			// aapt resource value: 0x7f050028
			public const int field_20 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int field_21 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int field_22 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int field_23 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int field_24 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int field_25 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int field_26 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int field_27 = 2131034159;
			
			// aapt resource value: 0x7f050020
			public const int field_30 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int field_31 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int field_32 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int field_33 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int field_34 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int field_35 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int field_36 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int field_37 = 2131034151;
			
			// aapt resource value: 0x7f050018
			public const int field_40 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int field_41 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int field_42 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int field_43 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int field_44 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int field_45 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int field_46 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int field_47 = 2131034143;
			
			// aapt resource value: 0x7f050010
			public const int field_50 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int field_51 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int field_52 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int field_53 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int field_54 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int field_55 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int field_56 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int field_57 = 2131034135;
			
			// aapt resource value: 0x7f050008
			public const int field_60 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int field_61 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int field_62 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int field_63 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int field_64 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int field_65 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int field_66 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int field_67 = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int field_70 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int field_71 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int field_72 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int field_73 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int field_74 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int field_75 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int field_76 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int field_77 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
